version: '2'

services:
  php:
    image: bitnami/php-fpm:latest
    #    image: phpstorm/php-73-apache-xdebug-27
    ports:
      - 9000:9000
    volumes:
      - ./web:/app
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - ./apache-vhost/myapp.conf:/vhosts/myapp.conf:ro
      - ./web:/app
