<?php
$verbs = [
    ["bake", "bakken", "bakte", "gebakken"],
    ["begin", "beginnen", "begon", "begonnen"],
    ["move", "bewegen", "bewoog", "bewogen"],
    ["offer", "bieden", "bood", "geboden"],
    ["bind", "binden", "bond", "gebonden"],
    ["appear", "blijken", "bleek", "gebleken"],
    ["break", "breken", "brak", "gebroken"],
    ["bring", "brengen", "bracht", "gebracht"],
    ["bend, bow", "buigen", "boog", "gebogen"],
    ["think", "denken", "dacht", "gedacht"],
    ["do", "doen", "deed", "gedaan"],
    ["carry, wear", "dragen", "droeg", "gedragen"],
    ["drink", "drinken", "dronk", "gedronken"],
    ["force", "dwingen", "dwong", "gedwongen"],
    ["eat", "eten", "at", "gegeten"],
    ["go", "gaan", "ging", "gegaan"],
    ["be valid", "gelden", "gold", "gegolden"],
    ["enjoy", "genieten", "genoot", "genoten"],
    ["give", "geven", "gaf", "gegeven"],
    ["hang", "hangen", "hing", "gehangen"],
    ["have", "hebben", "had", "gehad"],
    ["help", "helpen", "hielp", "geholpen"],
    ["be called", "heten", "heette", "geheten"],
    ["need (denying)", "hoeven", "hoefde", "gehoeven"],
    ["hold", "houden", "hield", "gehouden"],
    ["choose", "kiezen", "koos", "gekozen"],
    ["look, watch", "kijken", "keek", "gekeken"],
    ["sound", "klinken", "klonk", "geklonken"],
    ["come", "komen", "kwam", "gekomen"],
    ["buy", "kopen", "kocht", "gekocht"],
    ["can, be able to", "kunnen", "kon", "gekund"],
    ["laugh", "lachen", "lachte", "gelachen"],
    ["let", "laten", "liet", "gelaten"],
    ["read", "lezen", "las", "gelezen"],
    ["lay", "liggen", "lag", "gelegen"],
    ["look like", "lijken", "leek", "geleken"],
    ["walk", "lopen", "liep", "gelopen"],
    ["have to, must", "moeten", "moest", "gemoeten"],
    ["be allowed, may", "mogen", "mocht", "gemogen"],
    ["take", "nemen", "nam", "genomen"],
    ["call", "roepen", "riep", "geroepen"],
    ["give (poetic)", "schenken", "schonk", "geschonken"],
    ["create", "scheppen", "schiep", "geschapen"],
    ["shoot", "schieten", "schoot", "geschoten"],
    ["shift, push", "schuiven", "schoof", "geschoven"],
    ["beat", "slaan", "sloeg", "geslagen"],
    ["sleep", "slapen", "sliep", "geslapen"],
    ["close, shut", "sluiten", "sloot", "gesloten"],
    ["speak", "spreken", "sprak", "gesproken"],
    ["jump", "springen", "sprong", "gesprongen"],
    ["stand", "staan", "stond", "gestaan"],
    ["sting, stab", "steken", "stak", "gestoken"],
    ["die", "sterven", "stierf", "gestorven"],
    ["hit", "treffen", "trof", "getroffen"],
    ["pull", "trekken", "trok", "getrokken"],
    ["fall", "vallen", "viel", "gevallen"],
    ["catch", "vangen", "ving", "gevangen"],
    ["forget", "vergeten", "vergat", "vergeten"],
    ["loose", "verliezen", "verloor", "verloren"],
    ["find", "vinden", "vond", "gevonden"],
    ["fly", "vliegen", "vloog", "gevlogen"],
    ["prevent", "voorkómen", "voorkwam", "voorkomen"],
    ["happen", "vóórkomen", "kwam", "voor	voorgekomen"],
    ["ask", "vragen", "vroeg", "gevraagd"],
    ["know something", "weten", "wist", "geweten"],
    ["point", "wijzen", "wees", "gewezen"],
    ["win", "winnen", "won", "gewonnen"],
    ["become", "worden", "werd", "geworden"],
    ["say", "zeggen", "zei", "gezegd"],
    ["see", "zien", "zag", "gezien"],
    ["be", "zijn", "was", "geweest"],
    ["sing", "zingen", "zong", "gezongen"],
    ["sink", "zinken", "zonk", "gezonken"],
    ["sit", "zitten", "zat", "gezeten"],
    ["look for", "zoeken", "zocht", "gezocht"]
];
